[workspace]
resolver = "2"
members = ["crates/varve", "crates/varve-core"]

[workspace.package]
version = "0.6.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/pulseengine/varve"
authors = ["PulseEngine"]

[workspace.dependencies]
varve-core = { path = "crates/varve-core" }
